USE notesonfly;

create table USER (
USERNAME VARCHAR (50) NOT NULL,
FIRSTNAME VARCHAR (50),
LASTNAME VARCHAR (50),
EMAIL VARCHAR (50),
ADDRESS VARCHAR (100)
)

select * from USER

INSERT INTO USER (USERNAME) VALUES ("USER1")

INSERT INTO USER VALUES ("USER2", "FIRSTNAME", "LASTNAME", "EMAIL", "ADDRESS")

UPDATE USER
SET USERNAME = "DONTKNOW", FIRSTNAME = "DONTKNOW", LASTNAME = "DONTKNOW", EMAIL = "DONTKNOW", ADDRESS = "DONTKNOW"
WHERE USERNAME = "DONTKNOW"


DELETE FROM USER WHERE USERNAME = "vikrantsnirban"



create table NOTEBOOK (
USERNAME VARCHAR (50) NOT NULL,
NOTEBOOKNAME VARCHAR (50) NOT NULL
)

select* from Notebook

SELECT * FROM NOTEBOOK WHERE USERNAME = "vikrantsnirban"


create table NOTE (
USERNAME VARCHAR (50) NOT NULL,
NOTEBOOKNAME VARCHAR (50) NOT NULL,
NOTENAME VARCHAR (50) NOT NULL,
NOTETITLE VARCHAR (50),
NOTECONTENT VARCHAR (200)
)