name: build-s3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: AWS Credentials Setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Maven Build    
        run: mvn clean install
        
      - name: Push to S3
        run: aws s3 cp NotesOnFly-RestAPI/target/NotesOnFly-RestAPI-0.0.1-SNAPSHOT.jar s3://notesonfly

 
      

